apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-kibana
  template:
    metadata:
      labels:
        app: elasticsearch-kibana
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200

        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://localhost:9200"  # Connect to Elasticsearch via localhost
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5601

      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data