apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-kibana
  template:
    metadata:
      labels:
        app: elasticsearch-kibana
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"  # Increase heap size for better stability
            - name: xpack.security.enabled
              value: "true"  # Enable X-Pack Security for authentication
            - name: ELASTIC_PASSWORD
              value: "super_password"  # Set superuser password for `elastic` account
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200

        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://localhost:9200"  # Connect to Elasticsearch on localhost
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"  # Use the `elastic` superuser account
            - name: ELASTICSEARCH_PASSWORD
              value: "super_password"  # Use the same password as above
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5601

      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data