apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-kibana-service
  namespace: logging
spec:
  selector:
    app: elasticsearch-kibana  # This selector should match the labels in your Deployment
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200  # Port for Elasticsearch
    - name: kibana
      protocol: TCP
      port: 5601
      targetPort: 5601  # Port for Kibana
  type: NodePort  # Use NodePort to expose Kibana outside the cluster