apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi