apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: url
      value: https://github.com/SiddharthLucky/Kubernetes-Learning.git
    - name: revision
      value: main # or specify the branch you want to use